name: Prints the deployment result
description: Prints the deployment result including all the web/server/db urls
author: Mohammad Asghari mohammad.asghari@huma.com
branding:
  color: 'green'
  icon: 'package'
inputs:
  update_chart: { required: true, description: 'Update chart flag' }
  server_name: { required: true, description: 'Name of the project, such as dctserver' }
  host_prefix: { required: true, description: 'The root domain name for the deployment' }
  grafana_host: { required: true, description: 'The url of grafana host' }
  atlas_project_url: { required: true, description: 'Atlas project url' }
  atlas_project: { required: true, description: 'The name of the project in atlas' }
  atlas_cluster: { required: true, description: 'The cluster name of atlas' }
  app_name: { required: true, description: 'The domain prefix of the deployed app' }
  host_postfix: { required: true, description: 'The host prefix for mongo' }
  db_user: { required: true, description: 'Database username' }
  db_provider: { required: true, description: 'DB provider, e.g: atlas or kubedb' }
  db_username: { required: true, description: 'Database username' }
  db_password: { required: true, description: 'Database password' }
  mongo_uri: { required: true, description: 'Mongo URI' }
  dashboard_url: { required: true, description: 'Dashboard url' }
  bucket: { required: true, description: 'Bucket name' }
  bucket_provider: { required: true, description: 'The bucket provider, e.g: gcs, aws' }
  bucket_region: { required: true, description: 'Region of the bucket' }
outputs:
  result:
    description: The output text
    value: ${{ steps.template.outputs.result }}
runs:
  using: composite
  steps:
    - name: Copy template file
      shell: bash
      run: cat ${{ github.action_path }}/pr-preview-comment.tpl >> ./pr-preview-comment-copy.tpl
    - name: Render pr-preview-comment template
      id: template
      uses: chuhlomin/render-template@v1.6
      with:
        template: ./pr-preview-comment-copy.tpl
        vars: |-
          server_name: ${{ inputs.server_name}}
          url: "https://${{ inputs.app_name }}.${{ inputs.host_postfix }}"
          mongo_express_url: ${{ format('"https://{0}/mongo-express/db/{1}"',
            inputs.host_postfix, inputs.db_user) }}
          mongo_uri: ${{ inputs.db_provider == 'kubedb' &&
            format('"mongodb://{0}:{1}@{2}/{0}"',
            inputs.db_user, inputs.db_password, inputs.host_postfix) ||
            inputs.db_provider == 'atlas' && inputs.mongo_uri }}
          username: ${{ inputs.db_username }}
          password: ${{ inputs.db_password }}
          bucket_uri: ${{ format('"{0}://{1}"', inputs.bucket_provider == 'gcs' && 'gs' || 's3',
            inputs.bucket) }}
          console_url: ${{ inputs.bucket_provider == 'gcs' &&
            format('"[Google Cloud Console URL](https://console.cloud.google.com/storage/browser/{0})"',
            inputs.bucket) ||
            format('"[AWS Console URL](https://s3.console.aws.amazon.com/s3/buckets/{0}?region={1})"',
            inputs.bucket, inputs.bucket_region) }}
          dashboard_url: ${{ inputs.grafana_host }}${{ inputs.dashboard_url }}
          atlas_warning: ${{ inputs.db_provider == 'atlas' &&
            format('"- {0} `{1}` project [IP Access List]({2}#security/network/accessList)."',
            '**Note:** for Atlas Mongo Shell your IP should be on the',
            inputs.atlas_project, inputs.atlas_project_url) || '' }}
          atlas_cp: ${{ inputs.db_provider == 'atlas' &&
            format('"<br/>[Atlas Cluster control panel]({0}#clusters/detail/{1})."',
            inputs.atlas_project_url, inputs.atlas_cluster) || '' }}
    - name: Delete template file
      shell: bash
      run: rm ./pr-preview-comment-copy.tpl
