name: 'Helmfile diff with/without PR'
description: 'GH action to make a diff with input arguments and commenting on pull request if possible'
inputs:
  kubeconfig: 
    description: 'kubeconfig file path'
    required: true
  helmfile-folder:
    description: 'The folder of the helmfile'
    required: true
  helmfile-environment:
    description: 'The environment of the helmfile'
    required: true
    default: default
outputs:
  diff-output:
    description: 'helmfile diff output'
    value: ${{ env.diffbody }}
  comment-id:
    description: 'PR comment id'
    value: ${{ steps.cuc.outputs.comment-id }}

runs:
  using: "composite"
  steps:
    # Setup
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.0.0
      with:
        install-kubectl: no
        install-helm: no

    # Diff
    - name: Helmfile diff
      id: diffid
      shell: bash
      run: |
          export KUBECONFIG=${{ inputs.kubeconfig }}
          cd ${{ inputs.helmfile-folder }} && helmfile --no-color -e ${{ inputs.helmfile-environment }} -i diff > /tmp/diff.txt
          echo 'diffbody<<EOV' >> $GITHUB_ENV
          cat /tmp/diff.txt >> $GITHUB_ENV
          echo 'EOV' >> $GITHUB_ENV

    # PR commentator if possible
    - name: Find comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: '<summary>helmfile -e ${{ inputs.helmfile-environment }} -i diff</summary>'
    - name: Create or update comment
      if: github.event_name == 'pull_request'
      id: cuc
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### Diff
          <details>
            <summary>helmfile -e ${{ inputs.helmfile-environment }} -i diff</summary>

            ```diff
            ${{ env.diffbody }}
            ```
          </details>
        edit-mode: replace
