name: Publish coverage results
description: Publish coverage results

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Download tests
      uses: actions/download-artifact@v3
      with:
        name: pr-tests-coverage
    - name: Merge Tests Coverage Files
      run: |
        make common/git-tests-code-cov-pr-comment
      shell: bash
    - name: Find Comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: Coverage
      shell: bash
    - id: get-comment-body
      if: github.event_name == 'pull_request'
      run: |
        echo 'comment_body<<EOV' >> $GITHUB_ENV
        cat pr-tests-coverage.txt >> $GITHUB_ENV
        echo 'EOV' >> $GITHUB_ENV
      shell: bash
    - name: Create or update comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ env.comment_body }}
        edit-mode: replace
