name: Run the tests
description: Run the tests
inputs:
  server_name: { required: true, description: '' }
  include_sdk: { required: true, description: '' }
  sdk_ref: { required: true, description: '' }
  sdk_ssh_key: { required: true, description: '' }
  github_token: { required: true, description: '' }

runs:
  using: composite
  steps:
    - name: Clone repo
      uses: actions/checkout@v3
      with:
        submodules: true
        ssh-key: ${{ inputs.sdk_ssh_key }}

#    - name: Clone Submodule
#      if: ${{ inputs.include_sdk == 'true' }}
#      uses: actions/checkout@v3
#      with:
#        ssh-key: ${{ inputs.sdk_ssh_key }}
#        repository: huma-engineering/huma-server-sdk
#        path: libs/huma-server-sdk
#        ref: ${{ inputs.sdk_ref }}
    - name: Run Test Suit
      id: run_tests
      env:
        DOCKER_BUILDKIT: "1"
      run: make ${{ inputs.server_name }}/tests/docker-compose
      shell: bash
    - name: Store unit pytest results
      uses: actions/upload-artifact@v3
      with:
        name: unit-pytest.log
        path: ./testresults/unit-pytest.log
    - name: Store integration pytest results
      uses: actions/upload-artifact@v3
      with:
        name: integration-pytest.log
        path: ./testresults/integration-pytest.log
    - name: Store unit junit report
      uses: actions/upload-artifact@v3
      with:
        name: unit-junitresult.xml
        path: ./testresults/unit-junitresult.xml
    - name: Store integration junit report
      uses: actions/upload-artifact@v3
      with:
        name: integration-junitresult.xml
        path: ./testresults/integration-junitresult.xml
    - name: Publish code coverage results
      env:
        prNumber: ${{ github.event.pull_request.number }}
      run: |
        make common/git-full-tests-code-cov-pr-comment
        echo ${{ inputs.github_token }} | gh auth login --with-token
      shell: bash
    - name: Store Test Coverage
      uses: actions/upload-artifact@v3
      with:
        name: pr-tests-coverage
        path: pr-tests-coverage.txt
    - name: Store Tests Coverage XML Report
      if: steps.run_tests.outcome == 'success'
      uses: actions/upload-artifact@v3
      with:
        name: coverage-xml-report
        path: |
          ./testresults/coverage-unit-tests.xml
          ./testresults/coverage-integration-tests.xml
