name: Build and Push Docker Image

inputs:
  github_username:
    required: true
    type: string
  github_token:
    required: true
    type: string

outputs:
  short_sha:
    description: The short SHA of the commit used for the Docker image tag
    value: ${{ steps.get-short-sha.outputs.short_sha }}

runs:
  using: "composite"
  steps:
    - name: Get short SHA
      id: get-short-sha
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.github_username }}
        password: ${{ inputs.github_token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.SHORT_SHA }}
