name: Build and Push Docker Image

inputs:
  github_username:
    required: true
    type: string
  github_token:
    required: true
    type: string
  context:
    required: false
    type: string
    default: "."
  image_name:
    required: false
    type: string
    default: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
  image_tag_prefix:
    required: false
    type: string
    default: ""
  secrets:
    required: false
    type: string
    default: ""
outputs:
  short_sha:
    description: The short SHA of the commit used for the Docker image tag
    value: ${{ steps.get-short-sha.outputs.short_sha }}

runs:
  using: "composite"
  steps:
    - name: Get short SHA
      id: get-short-sha
      run: |-
        SHORT_SHA="${{ inputs.image_tag_prefix }}$(git rev-parse --short HEAD)"
        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
        echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.github_username }}
        password: ${{ inputs.github_token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ inputs.image_name }}:${{ env.SHORT_SHA }}
        secrets: ${{ inputs.secrets }}
