name: Build and Publish Docker Image
description: Build and publish a Docker image to GitHub Container Registry

inputs:
  github_username:
    description: "GitHub username for authentication"
    required: true
  github_token:
    description: "GitHub token for authentication"
    required: true
  context:
    description: "Docker build context path"
    required: false
    default: "."
  image_name:
    description: "Docker image name"
    required: false
    default: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
  image_tag_prefix:
    description: "Prefix for the Docker image tag"
    required: false
    default: ""
  image_tag_postfix:
    description: "Prefix for the Docker image tag"
    required: false
    default: ""
  secrets:
    description: "Docker build secrets"
    required: false
    default: ""
  build_args:
    description: "Docker build arguments (key=value pairs, one per line)"
    required: false
    default: ""
  dockerfile:
    description: "Path to Dockerfile"
    required: false
    default: "Dockerfile"
  target:
    description: "Target build stage"
    required: false
    default: ""
  platforms:
    description: "Platforms to build for (comma-separated, e.g., linux/amd64,linux/arm64)"
    required: false
    default: "linux/amd64"
  cache_from:
    description: "Cache sources (comma-separated, e.g., type=gha,type=registry)"
    required: false
    default: "type=gha"
  cache_to:
    description: "Cache destinations (comma-separated, e.g., type=gha,type=registry)"
    required: false
    default: "type=gha,mode=max"
  push:
    description: "Whether to push the image to registry"
    required: false
    default: "true"
outputs:
  image_tag:
    description: The short SHA of the commit used for the Docker image tag
    value: ${{ steps.get-image-tag.outputs.IMAGE_TAG }}
  image_digest:
    description: The digest of the built image
    value: ${{ steps.build.outputs.digest }}
  image_id:
    description: The ID of the built image
    value: ${{ steps.build.outputs.imageid }}

runs:
  using: "composite"
  steps:
    - name: Get image tag for Docker image
      id: get-image-tag
      shell: bash
      run: |
        prefix="${{ inputs.image_tag_prefix }}"
        postfix="${{ inputs.image_tag_postfix }}"
        tag="${GITHUB_SHA::7}"
        [ -n "$prefix" ] && tag="$prefix-$tag"
        [ -n "$postfix" ] && tag="$tag-$postfix"
        echo "IMAGE_TAG=$tag" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.github_username }}
        password: ${{ inputs.github_token }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        target: ${{ inputs.target }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        build-args: ${{ inputs.build_args }}
        cache-from: ${{ inputs.cache_from }}
        cache-to: ${{ inputs.cache_to }}
        secrets: ${{ inputs.secrets }}
