name: "Helmfile apply"
description: "GH action for applying the helmfile on the given environment"
inputs:
  helmfile_workdirectory:
    description: "The folder of the helmfile"
    required: true
  helmfile_environment:
    description: "The environment of the helmfile"
    required: true
  kubeconfig:
    description: "base64 encoded kubeconfig file content"
    required: true
  helmfile_extra_args:
    description: "The arguments of the helmfile"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up kubeconfig
      shell: bash
      run: |
        mkdir -p ~/.kube
        echo ${{ inputs.kubeconfig }} | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Log in to GitHub Container Registry for Helm
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo $GITHUB_TOKEN | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Deploy with Helmfile
      uses: helmfile/helmfile-action@v2.0.5
      with:
        helmfile-args: apply --environment ${{ inputs.helmfile_environment }} --context 5 ${{ inputs.helmfile_extra_args }}
        helmfile-workdirectory: ${{ inputs.helmfile_workdirectory }}