name: Do checks, show confirmation comment
description: Do checks, show confirmation comment
inputs:
  include_sdk: { required: true, description: '' }
  sdk_ref: { required: true, description: '' }
  sdk_ssh_key: { required: true, description: '' }
  github_token: { required: true, description: '' }
  make_build_push_ghcr: { required: true, description: '' }
  issue_number: { required: true, description: '' }
  head_sha: { required: true, description: '' }
  head_ref: { required: true, description: '' }

runs:
  using: composite
  steps:
    - name: Clone repo
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.head_sha }}
    - name: Clone Submodule
      if: ${{ inputs.include_sdk }}
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ inputs.sdk_ssh_key }}
        repository: huma-engineering/huma-server-sdk
        path: libs/huma-server-sdk
        ref: ${{ inputs.sdk_ref }}
    - name: Login to ghcr
      run: echo ${{ inputs.github_token }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash
    - name: Build and Push to ghcr
      id: build
      env:
        DOCKER_BUILDKIT: "1"
      run: |-
        make ${{ inputs.make_build_push_ghcr }} && error=0 || error=$?
        echo "::set-output name=error::$error"
      shell: bash

    - name: Report on build success
      if: steps.build.outputs.error == 0
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ inputs.issue_number }}
        body: |-
          Built a new version of the container from the branch `${{ inputs.head_ref }}`,
          commit ${{inputs.head_sha}}, and pushed it to GHCR.👌

    - name: Report on build failure
      if: steps.build.outputs.error != 0
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ inputs.issue_number }}
        body: |-
          Failed to build and push container from the branch `${{ inputs.head_ref }}`,
          commit ${{inputs.head_sha}}.❌
