style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/huma-engineering/huma-common-actions
options:
  commits:
    sort_by: Type
    filters:
      Type:
        - feat
        - fix
        - improvement
        - docs
        - ref
        - test
        - ci
  commit_groups:
    group_by: Type
    sort_by: Custom
    title_order:
      - feat
      - improvement
      - ref
      - fix
      - docs
      - test
      - ci
    title_maps:
      feat: FEATURES
      fix: BUG FIXES
      improvement: ENHANCEMENTS
      docs: DOCS
      ref: REFACTORS
      test: TESTS
      ci: CI
  header:
    pattern: "^(.+)\\s*:\\s*(.+)$"
    pattern_maps:
      - Type
      - Subject
  issues:
    prefix:
      -  #
  notes:
    keywords:
      - BREAKING CHANGES
      - NOTES
  refs:
    actions:
      - Closes
      - Fixes
      - Resolves
