name: Uninstall a Helm chart
# ref: https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/
description: Uninstall a Helm chart
author: Denis Trofimov denis.trofimov@huma.com
branding:
  color: 'purple'
  icon: 'x-square'
inputs:
  cluster_name:
    description: GKE cluster name
    required: true
  gcp_credentials:
    description: GCP Service Account Key
    required: true
  location:
    description: GKE zone
    required: true
  app_name:
    description: Application Deployment name
    required: true
  app_namespace:
    description: Application namespace
    required: true
  delete_namespace:
    description: Delete namespace
    required: false
    default: 'false'
outputs:
  error:
    description: action's exit code
    value: ${{ steps.helm.outputs.error }}
runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud via a Service Account Key JSON
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: Get the GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.location }}

    - name: Uninstall a Helm chart
      id: helm
      run: |
        helm uninstall ${{ inputs.app_name }} -n ${{ inputs.app_namespace }} && error=0 || error=$?
        echo "::set-output name=error::$error"
      shell: bash

    - name: Delete namespace
      if: inputs.delete_namespace != 'false'
      run: kubectl delete namespace ${{ inputs.app_namespace }} --wait=false || exit 0
      shell: bash
