environments:
  default:
    values:
      - namespace: default
  dev:
    values:
      - namespace: dev

---

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: test-nginx
    chart: bitnami/nginx
    version: 15.14.0
    namespace: "{{ .Values.namespace }}"
    values:
      - service:
          type: ClusterIP