name: Test helmfile-pr action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start minikube
        run: |
          minikube start
<<<<<<< HEAD
      - name: Helmfile
        run: |
          minikube start
          kubectl get po -A



      # - name: Run p81 vpn connection
      #   id: p81_id
      #   uses: ./openvpn-p81
      #   with:
      #     configfile-url: ${{ secrets.VPN_CONFIGFILEURL }}
      #     username: ${{ secrets.VPN_USERNAME }}
      #     password: ${{ secrets.VPN_PASSWORD }}
      
      
=======
          minikube kubectl config view >> $HOME/.kubeconfig
      - name: Run PR helmfile for default environment
        id: prid
        uses: ./helmfile-pr-diff
        with:
          kubeconfig: $HOME/.kubeconfig
          helmfile-folder: ./examples/helmfile-pr

      - name: Run PR helmfile for dev environment
        id: prdevid
        uses: ./helmfile-pr-diff
        with:
          kubeconfig: $HOME/.kubeconfig
          helmfile-folder: ./examples/helmfile-pr
          helmfile-environment: dev

      - name: Run helmfile apply for default environment
        uses: ./helmfile-apply
        with:
          kubeconfig: $HOME/.kubeconfig
          helmfile-folder: ./examples/helmfile-pr

      - name: Run helmfile apply for dev environment
        uses: ./helmfile-apply
        with:
          kubeconfig: $HOME/.kubeconfig
          helmfile-folder: ./examples/helmfile-pr
          comment-id: ${{ steps.prdevid.outputs.comment-id }}
>>>>>>> 8b1c987e1dab0e103c27829cfb621f40102abf4b
