name: Pull request Ops commands help

on:
  workflow_call:
    inputs:
      server_name:
        required: true
        type: string

jobs:
  help:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/workflows/help-sdk-pr-preview.md

      - name: help
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |-
            ${{ steps.template.outputs.result }}
