name: Test p81vpn action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run p81 vpn connection
        id: p81_id
        uses: ./openvpn-p81
        with:
          configfile-url: ${{ secrets.VPN_CONFIGFILEURL }}
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}
      
      - name: Print vpn ip which is the same github action runner
        run: |
          echo "vpn gateway ip is" ${{ steps.p81_id.outputs.ip }}
          echo $(curl ifconfig.me)
        
