name: Test helmfile-pr-diff action

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test-helmfile-pr-diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start minikube
        run: |
          minikube start
          minikube kubectl config view > $HOME/.kubeconfig
          
      - name: Encode kubeconfig
        id: kubeconfig
        run: |
          echo "kubeconfig_base64=$(base64 -w 0 $HOME/.kubeconfig)" >> $GITHUB_OUTPUT
          
      - name: Run PR helmfile for default environment
        id: prid
        uses: ./helmfile-pr-diff
        with:
          kubeconfig: $HOME/.kubeconfig
          helmfile-folder: ./examples/helmfile-pr

      - name: Run PR helmfile for dev environment
        id: prdevid
        uses: ./helmfile-pr-diff
        with:
          kubeconfig: $HOME/.kubeconfig
          helmfile-folder: ./examples/helmfile-pr
          helmfile-environment: dev

      - name: Run helmfile apply for default environment
        uses: ./helmfile-apply
        with:
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig_base64 }}
          helmfile-folder: ./examples/helmfile-pr
          helmfile-environment: default

      - name: Run helmfile apply for dev environment
        uses: ./helmfile-apply
        with:
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig_base64 }}
          helmfile-folder: ./examples/helmfile-pr
          helmfile-environment: dev
