name: Test hello action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test-hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run hello action
        id: hello_id
        uses: ./hello
        with:
          who-to-greet: "Brown fox!"
      
      - name: Test ouptut of hello action
        run: |
          echo ${{ steps.hello_id.outputs.random-number }}
        
