name: Test helmfile-pr-diff action

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test-helmfile-pr-diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start minikube
        run: |
          minikube start
          minikube kubectl config view >> $HOME/.kubeconfig
      - name: Run PR helmfile for default environment
        id: prid
        uses: ./helmfile-pr-diff
        with:
          kubeconfig: $HOME/.kubeconfig
          helmfile-folder: ./examples/helmfile-pr

      - name: Run PR helmfile for dev environment
        id: prdevid
        uses: ./helmfile-pr-diff
        with:
          install-helm-plugins: no
          kubeconfig: $HOME/.kubeconfig
          helmfile-folder: ./examples/helmfile-pr
          helmfile-environment: dev

      - name: Run helmfile apply for default environment
        uses: ./helmfile-apply
        with:
          install-helm-plugins: no
          kubeconfig: $HOME/.kubeconfig
          helmfile-folder: ./examples/helmfile-pr

      - name: Run helmfile apply for dev environment
        uses: ./helmfile-apply
        with:
          install-helm-plugins: no
          kubeconfig: $HOME/.kubeconfig
          helmfile-folder: ./examples/helmfile-pr
          comment-id: ${{ steps.prdevid.outputs.comment-id }}
